# Generated by Django 4.2.3 on 2023-07-24 16:51

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Children',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('sexe', models.CharField(choices=[('F', 'Feminin'), ('M', 'Masculin')], max_length=1, validators=[django.core.validators.RegexValidator('^[FM]$')])),
                ('parent', models.CharField(max_length=100)),
                ('tel', models.CharField(max_length=20)),
                ('email_parent', models.EmailField(max_length=254)),
                ('date_naissance', models.DateField()),
                ('photo', models.ImageField(upload_to='upload_to')),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('section', models.CharField(choices=[('Petite', 'Petite'), ('Moyenne', 'Moyenne'), ('Grande', 'Grande')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('section', models.CharField(choices=[('Petite', 'Petite'), ('Moyenne', 'Moyenne'), ('Grande', 'Grande')], max_length=100)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.DecimalField(decimal_places=2, max_digits=3)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('children', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LB_App.children')),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LB_App.cours')),
            ],
        ),
    ]
