# Generated by Django 4.2.3 on 2023-07-24 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LB_App', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='note',
        ),
        migrations.AddField(
            model_name='note',
            name='chant',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='dessin',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='ecriture',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
    ]
