# Generated by Django 4.2.3 on 2023-07-24 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LB_App', '0003_remove_note_cours_delete_cours'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='chant',
            new_name='note_chant',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='dessin',
            new_name='note_dessin',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='ecriture',
            new_name='note_ecriture',
        ),
    ]
