# Generated by Django 4.2.3 on 2023-07-25 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LB_App', '0004_rename_chant_note_note_chant_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_complet', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('objet', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
